kind: ReplicationController
apiVersion: v1
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  replicas: 2
  selector:
    name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - name: postgres
        image: itduluk/postgres:v1.0.0
        ports:
        - containerPort: 5436
          protocol: TCP
